
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLASS_NAME CLASS_STEREOTYPE DATA_TYPE INSTANCE_NAME NEW_TYPE NUMBER RELATION_NAME RELATION_STEREOTYPE RESERVED_WORD SPECIAL_SYMBOLprogram : package_decl elementospackage_decl : RESERVED_WORD CLASS_NAME\n    elementos : elementos elemento\n              | elemento\n    \n    elemento : class_decl\n             | datatype_decl\n             | enum_decl\n             | generalizacao\n             | relation_decl\n    \n    class_decl : CLASS_STEREOTYPE CLASS_NAME SPECIAL_SYMBOL atributos SPECIAL_SYMBOL\n               | CLASS_STEREOTYPE CLASS_NAME SPECIAL_SYMBOL SPECIAL_SYMBOL\n    \n    atributos : atributos atributo\n              | atributo\n    atributo : RELATION_NAME SPECIAL_SYMBOL tipo\n    tipo : DATA_TYPE\n         | NEW_TYPE\n         | CLASS_NAME\n    datatype_decl : NEW_TYPE SPECIAL_SYMBOL atributos SPECIAL_SYMBOLenum_decl : RESERVED_WORD CLASS_NAME SPECIAL_SYMBOL lista_enum SPECIAL_SYMBOL\n    lista_enum : lista_enum SPECIAL_SYMBOL CLASS_NAME\n               | CLASS_NAME\n    generalizacao : RESERVED_WORD RESERVED_WORD RESERVED_WORD CLASS_NAME RESERVED_WORD class_list\n    class_list : CLASS_NAME\n               | class_list SPECIAL_SYMBOL CLASS_NAME\n    generalizacao : RESERVED_WORD CLASS_NAME SPECIAL_SYMBOL general_block SPECIAL_SYMBOL\n    general_block : general_spec specifics_spec\n    general_spec : RESERVED_WORD CLASS_NAMEspecifics_spec : RESERVED_WORD class_list\n    relation_decl : opt_at SIGNED_RELATION\n                 | RELATION_STEREOTYPE SIGNED_RELATION\n                 | RESERVED_WORD SIGNED_RELATION\n    opt_at : SPECIAL_SYMBOL\n    SIGNED_RELATION : RELATION_STEREOTYPE relation_body\n                    | RESERVED_WORD relation_body\n                    | relation_body\n    \n    relation_body : CLASS_NAME relation_symbol CLASS_NAME\n                  | CLASS_NAME\n    relation_symbol : SPECIAL_SYMBOL'
    
_lr_action_items = {'RESERVED_WORD':([0,2,4,5,6,7,8,9,10,12,14,15,16,17,18,21,22,23,25,26,28,29,35,36,38,40,42,45,50,51,52,58,59,60,63,64,68,],[3,14,14,-4,-5,-6,-7,-8,-9,-32,21,27,27,-2,-3,34,-37,-31,-35,-29,-37,-30,-34,46,-33,-11,-18,57,62,-36,-10,-27,-19,-25,-23,-22,-24,]),'$end':([1,4,5,6,7,8,9,10,18,22,23,25,26,28,29,35,38,40,42,51,52,59,60,63,64,68,],[0,-1,-4,-5,-6,-7,-8,-9,-3,-37,-31,-35,-29,-37,-30,-34,-33,-11,-18,-36,-10,-19,-25,-23,-22,-24,]),'CLASS_STEREOTYPE':([2,4,5,6,7,8,9,10,17,18,22,23,25,26,28,29,35,38,40,42,51,52,59,60,63,64,68,],[11,11,-4,-5,-6,-7,-8,-9,-2,-3,-37,-31,-35,-29,-37,-30,-34,-33,-11,-18,-36,-10,-19,-25,-23,-22,-24,]),'NEW_TYPE':([2,4,5,6,7,8,9,10,17,18,22,23,25,26,28,29,35,38,40,42,44,51,52,59,60,63,64,68,],[13,13,-4,-5,-6,-7,-8,-9,-2,-3,-37,-31,-35,-29,-37,-30,-34,-33,-11,-18,55,-36,-10,-19,-25,-23,-22,-24,]),'RELATION_STEREOTYPE':([2,4,5,6,7,8,9,10,12,14,15,16,17,18,22,23,25,26,28,29,35,38,40,42,51,52,59,60,63,64,68,],[16,16,-4,-5,-6,-7,-8,-9,-32,24,24,24,-2,-3,-37,-31,-35,-29,-37,-30,-34,-33,-11,-18,-36,-10,-19,-25,-23,-22,-24,]),'SPECIAL_SYMBOL':([2,4,5,6,7,8,9,10,13,17,18,19,22,23,25,26,28,29,30,31,32,33,35,38,40,41,42,43,47,48,49,51,52,53,54,55,56,59,60,61,63,64,65,66,68,],[12,12,-4,-5,-6,-7,-8,-9,20,-2,-3,30,36,-31,-35,-29,39,-30,40,42,-13,44,-34,-33,-11,52,-18,-12,-21,59,60,-36,-10,-14,-15,-16,-17,-19,-25,-26,-23,67,-20,67,-24,]),'CLASS_NAME':([3,11,12,14,15,16,21,24,27,34,36,37,39,44,46,57,59,62,67,],[17,19,-32,22,28,28,28,28,28,45,47,51,-38,56,58,63,65,63,68,]),'RELATION_NAME':([20,30,31,32,41,43,53,54,55,56,],[33,33,33,-13,33,-12,-14,-15,-16,-17,]),'DATA_TYPE':([44,],[54,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'package_decl':([0,],[2,]),'elementos':([2,],[4,]),'elemento':([2,4,],[5,18,]),'class_decl':([2,4,],[6,6,]),'datatype_decl':([2,4,],[7,7,]),'enum_decl':([2,4,],[8,8,]),'generalizacao':([2,4,],[9,9,]),'relation_decl':([2,4,],[10,10,]),'opt_at':([2,4,],[15,15,]),'SIGNED_RELATION':([14,15,16,],[23,26,29,]),'relation_body':([14,15,16,21,24,27,],[25,25,25,35,38,35,]),'atributos':([20,30,],[31,41,]),'atributo':([20,30,31,41,],[32,32,43,43,]),'relation_symbol':([22,28,],[37,37,]),'lista_enum':([36,],[48,]),'general_block':([36,],[49,]),'general_spec':([36,],[50,]),'tipo':([44,],[53,]),'specifics_spec':([50,],[61,]),'class_list':([57,62,],[64,66,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> package_decl elementos','program',2,'p_program','parser_tonto.py',20),
  ('package_decl -> RESERVED_WORD CLASS_NAME','package_decl',2,'p_package_decl','parser_tonto.py',27),
  ('elementos -> elementos elemento','elementos',2,'p_elementos','parser_tonto.py',39),
  ('elementos -> elemento','elementos',1,'p_elementos','parser_tonto.py',40),
  ('elemento -> class_decl','elemento',1,'p_elemento','parser_tonto.py',50),
  ('elemento -> datatype_decl','elemento',1,'p_elemento','parser_tonto.py',51),
  ('elemento -> enum_decl','elemento',1,'p_elemento','parser_tonto.py',52),
  ('elemento -> generalizacao','elemento',1,'p_elemento','parser_tonto.py',53),
  ('elemento -> relation_decl','elemento',1,'p_elemento','parser_tonto.py',54),
  ('class_decl -> CLASS_STEREOTYPE CLASS_NAME SPECIAL_SYMBOL atributos SPECIAL_SYMBOL','class_decl',5,'p_class_decl','parser_tonto.py',64),
  ('class_decl -> CLASS_STEREOTYPE CLASS_NAME SPECIAL_SYMBOL SPECIAL_SYMBOL','class_decl',4,'p_class_decl','parser_tonto.py',65),
  ('atributos -> atributos atributo','atributos',2,'p_atributos','parser_tonto.py',86),
  ('atributos -> atributo','atributos',1,'p_atributos','parser_tonto.py',87),
  ('atributo -> RELATION_NAME SPECIAL_SYMBOL tipo','atributo',3,'p_atributo','parser_tonto.py',96),
  ('tipo -> DATA_TYPE','tipo',1,'p_tipo','parser_tonto.py',102),
  ('tipo -> NEW_TYPE','tipo',1,'p_tipo','parser_tonto.py',103),
  ('tipo -> CLASS_NAME','tipo',1,'p_tipo','parser_tonto.py',104),
  ('datatype_decl -> NEW_TYPE SPECIAL_SYMBOL atributos SPECIAL_SYMBOL','datatype_decl',4,'p_datatype_decl','parser_tonto.py',113),
  ('enum_decl -> RESERVED_WORD CLASS_NAME SPECIAL_SYMBOL lista_enum SPECIAL_SYMBOL','enum_decl',5,'p_enum_decl','parser_tonto.py',123),
  ('lista_enum -> lista_enum SPECIAL_SYMBOL CLASS_NAME','lista_enum',3,'p_lista_enum','parser_tonto.py',132),
  ('lista_enum -> CLASS_NAME','lista_enum',1,'p_lista_enum','parser_tonto.py',133),
  ('generalizacao -> RESERVED_WORD RESERVED_WORD RESERVED_WORD CLASS_NAME RESERVED_WORD class_list','generalizacao',6,'p_generalizacao_inline','parser_tonto.py',148),
  ('class_list -> CLASS_NAME','class_list',1,'p_class_list','parser_tonto.py',162),
  ('class_list -> class_list SPECIAL_SYMBOL CLASS_NAME','class_list',3,'p_class_list','parser_tonto.py',163),
  ('generalizacao -> RESERVED_WORD CLASS_NAME SPECIAL_SYMBOL general_block SPECIAL_SYMBOL','generalizacao',5,'p_generalizacao_block','parser_tonto.py',173),
  ('general_block -> general_spec specifics_spec','general_block',2,'p_general_block','parser_tonto.py',182),
  ('general_spec -> RESERVED_WORD CLASS_NAME','general_spec',2,'p_general_spec','parser_tonto.py',187),
  ('specifics_spec -> RESERVED_WORD class_list','specifics_spec',2,'p_specifics_spec','parser_tonto.py',193),
  ('relation_decl -> opt_at SIGNED_RELATION','relation_decl',2,'p_relation_decl','parser_tonto.py',205),
  ('relation_decl -> RELATION_STEREOTYPE SIGNED_RELATION','relation_decl',2,'p_relation_decl','parser_tonto.py',206),
  ('relation_decl -> RESERVED_WORD SIGNED_RELATION','relation_decl',2,'p_relation_decl','parser_tonto.py',207),
  ('opt_at -> SPECIAL_SYMBOL','opt_at',1,'p_opt_at','parser_tonto.py',221),
  ('SIGNED_RELATION -> RELATION_STEREOTYPE relation_body','SIGNED_RELATION',2,'p_signed_relation','parser_tonto.py',229),
  ('SIGNED_RELATION -> RESERVED_WORD relation_body','SIGNED_RELATION',2,'p_signed_relation','parser_tonto.py',230),
  ('SIGNED_RELATION -> relation_body','SIGNED_RELATION',1,'p_signed_relation','parser_tonto.py',231),
  ('relation_body -> CLASS_NAME relation_symbol CLASS_NAME','relation_body',3,'p_relation_body','parser_tonto.py',240),
  ('relation_body -> CLASS_NAME','relation_body',1,'p_relation_body','parser_tonto.py',241),
  ('relation_symbol -> SPECIAL_SYMBOL','relation_symbol',1,'p_relation_symbol','parser_tonto.py',254),
]
